# Cotire.cmake 1.8.0 generated file
# /home/xieyang/workspace/openMVS/MyBuild/libs/IO/IO_CXX_Cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/xieyang/workspace/openMVS/build/Cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "CMakeTargets")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "_USE_OPENMP;_USE_OPENGL;_USE_BOOST;_USE_EIGEN;_USE_NONFREE;_USE_FAST_FLOAT2INT;_USE_FAST_CBRT;_USE_SSE;_USE_PNG;_USE_JPG;_USE_TIFF;_LIB;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "-W;-Wall;-Werror=address;-Werror=sequence-point;-Wformat;-Werror=format-security;-Winit-self;-Wsign-promo;-Wreorder;-Wno-undef;-Wno-switch;-Wno-switch-enum;-Wno-switch-default;-Wno-comment;-Wno-narrowing;-Wno-attributes;-Wno-enum-compare;-Wno-missing-field-initializers;-Wno-unused-parameter;-Wno-delete-incomplete;-fdiagnostics-show-option;-ftemplate-backtrace-limit=0;-Wno-long-long;-pthread;-fomit-frame-pointer;-frounding-math;-msse;-msse2;-msse3;-mssse3;-msse4.1;-msse4.2;-ffunction-sections;-fopenmp;-O3;-W;-Wall;-Werror=address;-Werror=sequence-point;-Wformat;-Werror=format-security;-Winit-self;-Wsign-promo;-Wreorder;-Wno-undef;-Wno-switch;-Wno-switch-enum;-Wno-switch-default;-Wno-comment;-Wno-narrowing;-Wno-attributes;-Wno-enum-compare;-Wno-missing-field-initializers;-Wno-unused-parameter;-Wno-delete-incomplete;-fdiagnostics-show-option;-ftemplate-backtrace-limit=0;-Wno-long-long;-pthread;-fomit-frame-pointer;-frounding-math;-msse;-msse2;-msse3;-mssse3;-msse4.1;-msse4.2;-ffunction-sections;-Wall;-fexceptions;-std=gnu++11")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Release")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/xieyang/workspace/openMVS")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "/home/xieyang/workspace/openMVS;/usr/local/include/eigen3;/usr/include/opencv;/usr/include/x86_64-linux-gnu")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/xieyang/workspace/openMVS/libs/IO/Common.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageEXIF.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageSCI.cpp;/home/xieyang/workspace/openMVS/libs/IO/PLY.cpp;/home/xieyang/workspace/openMVS/libs/IO/Image.cpp;/home/xieyang/workspace/openMVS/libs/IO/OBJ.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageTGA.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageTIFF.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageDDS.cpp;/home/xieyang/workspace/openMVS/libs/IO/TinyXML2.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImagePNG.cpp;/home/xieyang/workspace/openMVS/libs/IO/EXIF.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageJPG.cpp;/home/xieyang/workspace/openMVS/libs/IO/ImageBMP.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Release")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "5.4.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
